name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          sudo pip3 install coverage pytest pytest-cov codecov toml colored

      - name: Build
        run: make

      - name: Re Build
        run: make re

      - name: Launching Unit Tests
        run: make all_unit_tests

      - name: Upload Coverage
        env:
          CODECOV_TOKEN: "0dca2275-7080-4e3a-9438-b14a8b727399"
        run: curl -s https://codecov.io/bash | bash

  blih:
    runs-on: ubuntu-latest
    needs: build
    env:
      USER_GHUB: "Encorpluptit"
      USER_BLIH: "damien.bernard@epitech.eu"
    steps:
      - uses: actions/checkout@v2
      - run: |
          which ssh-agent || ( sudo apt-get update -y && sudo apt-get install openssh-client -y)
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa && echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: Set Github Repo Name in env
        run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
        shell: bash
      - name: Push Blih
        run: bash ./.github/scripts/GithubToBlih.sh $REPOSITORY_NAME
        shell: bash
